personalWeb/base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path('', views.landing, name="landing"),
    path('adminPage/', views.adminPage, name='adminPage'),
    path('contact/', views.contact, name="contact"),
    path('resume/', views.resume, name="resume"),
    path('ibm/', views.ibm, name="ibm"),
    path('publication/', views.publication, name="publication"),
    path('eid101/', views.eid101, name="eid101"),
    path('contact_submit/', views.contact_submit, name='contact_submit'),
    path('ml/', views.mlproj, name="mlproj"),
    path('cert/', views.cert, name="cert"),
    path('home/', views.home, name="home"),
    path('about/', views.about, name="about"),
    #path('room/', views.room, name="room"),

    #Change when uploading full web
    path('todo/', views.todo, name="todo"),
    path('hac/', views.hac, name="hac"),
    path('utube/', views.utube, name="utube"),

]

personalWeb/personalWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personalWeb/base/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    # Django model fields
    title = models.CharField(max_length = 100)
    description = models.CharField(max_length = 1000)
    image = models.ImageField(upload_to ='media/')
    url = models.URLField(blank = True)
    
    # Functions that displays title on the admin page
    def __str__(self):
        return self.title

class Skill(models.Model):
    title = models.CharField(max_length=50)
    def __str__(self):
        return self.title

class Publication(models.Model):
    # Django model fields
    title = models.CharField(max_length = 500)
    description = models.TextField()
    image = models.ImageField(upload_to ='media/')
    url = models.URLField(blank = True)
    
    # Functions that displays title on the admin page
    def __str__(self):
        return self.title

class ContactForm(models.Model):
    first_name = models.CharField(max_length=255, default='')
    last_name = models.CharField(max_length=255, default='')
    email = models.EmailField(default='')
    phone_number = models.CharField(max_length=255, default='')
    find = models.CharField(max_length=255, default='')
    additional_info = models.TextField(default='')
    file = models.FileField(upload_to='media/', default=None, blank=True, null=True)
    terms = models.BooleanField(default=False)

    def __str__(self):
        return self.email

class ML(models.Model):
    # Django model fields
    title = models.CharField(max_length = 250)
    description = models.TextField()
    tech = models.TextField()
    image = models.ImageField(upload_to ='media/')
    url = models.URLField(blank = True)
    
    # Functions that displays title on the admin page
    def __str__(self):
        return self.title

class Cert(models.Model):
    # Django model fields
    title = models.CharField(max_length = 250)
    date = models.DateField()
    url = models.URLField(blank = True)
    
    # Functions that displays title on the admin page
    def __str__(self):
        return self.title

personalWeb/base/views.py
from django.shortcuts import render
from .models import Project, Publication, Skill, ContactForm, ML, Cert


# Create your views here.
def home(request):
    projects = Project.objects.all()
    skills = Skill.objects.all().order_by('title')
    context = {'projects': projects, 'skills': skills}
    return render(request, 'base/home.html', context)

def publication(request):
    publications = Publication.objects.all()
    context = {'publications': publications}
    return render(request, 'base/publication.html', context)

def contact(request):
    return render(request, 'base/contact.html')

def resume(request):
    return render(request, 'base/resume.html')

def about(request):
    return render(request, 'base/about.html')

def ibm(request):
    return render(request, 'base/IBMppt.html')

def eid101(request):
    return render(request, 'base/eid101.html')

def cert(request):
    certs = Cert.objects.all()
    context = {'certs': certs}
    return render(request, 'base/cert.html', context)

def landing(request):
    return render(request, 'base/landing.html')

# Admin
from django.urls import reverse
from django.shortcuts import redirect

def adminPage(request):
    admin_url = reverse('admin:index')
    return redirect(admin_url)

def mlproj(request):
    MLs = ML.objects.all()
    context = {'MLs': MLs}
    return render(request, 'base/mlproj.html', context)

def contact_submit(request):
    if request.method == 'POST':
        first_name = request.POST.get('firstName')
        last_name = request.POST.get('lastName')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        find = request.POST.get('find')
        info = request.POST.get('textBox')
        file = request.FILES.get('file')
        term = request.POST.get('term') == "on"

        contact_form = ContactForm(
        first_name=first_name,
        last_name=last_name,
        email=email,
        phone_number=phone,
        find=find,
        additional_info=info,
        file=file,
        terms=term
        )

        contact_form.save()

        # Do something with the form data, such as sending an email or saving it to the database
        
        # Redirect to a success page
        return render(request, 'base/contact_submit.html')

    # If the request is not a POST, return the form template
    return render(request, 'base/contact.html')

# Delete when uploading full web

def todo(request):
    return render(request, 'base/todo.html')
    
def utube(request):
    return render(request, 'base/utube.html')

def hac(request):
    return render(request, 'base/hac.html')

personalWeb/base/templates/base/IBMppt.html
{% extends 'main.html'%} {% load static %} {% block content %}
<div class="container text-center">
  <h2>IBM Data Science Capstone Presentation</h2>
</div>

<div class="container text-center">
  <iframe
    src="{% static 'base/IBMppt.pdf' %}"
    frameborder="0"
    width="1100"
    height="670"
    >IBM</iframe
  >
</div>

<hr />

<div class="container">
  <h2>Python Libraries Used</h2>
  <ul>
    <li>Dash</li>
    <li>Folium</li>
    <li>Pandas</li>
    <li>Plotly</li>
    <li>Seaborn</li>
    <li>Scikit-learn</li>
  </ul>
</div>

<hr />

{% endblock %}

personalWeb/base/templates/base/about.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%} {% load static %} {% block content %}

<!--- Adding Publication Model -->

<div class="container" style="width: 50%">
  <h3 class="text-center">About me</h3>
  <p style="text-indent: 2em; text-align: justify">
    I am a recent graduate of Cooper Union, where I obtained a Bachelor of
    Engineering degree. I am currently working at Intel as a Process Engineer,
    where I am responsible for developing and improving manufacturing processes
    to enhance the efficiency and quality of Intel's products. While I am
    passionate about engineering, I am also deeply interested in data science
    and development. I have always been fascinated by the power of data and its
    ability to reveal insights and inform decisions.
  </p>
  <p style="text-indent: 2em; text-align: justify">
    In today's world, data is a critical resource that can drive innovation,
    improve operations, and create new opportunities. My experience at Intel has
    given me a strong foundation in engineering, which I believe will be
    invaluable in my pursuit of a career in data science or development. As an
    engineer, I have honed my skills in problem-solving, critical thinking, and
    data analysis, all of which are essential skills for a successful data
    scientist or developer.
  </p>
  <p style="text-indent: 2em; text-align: justify">
    In my spare time, I enjoy exploring new technologies and learning new
    skills. I have taught myself programming languages such as Python,
    Javascript, and C++, and have completed several online courses in data
    science and machine learning. I am always looking for new challenges and
    opportunities to grow my skills and knowledge. As I look to the future, I am
    excited about the possibilities that lie ahead. Whether it's developing
    cutting-edge technologies or unlocking insights from data, I am eager to
    contribute my skills and expertise to make a meaningful impact. Thank you
    for taking the time to learn more about me, and I look forward to connecting
    with you!
  </p>
</div>

<hr />

<div class="container">
  <div class="row">
    <h1 class="text-center" style="padding: 20px">About the Website</h1>
    <br />
    <div class="col-6">
      <img
        src="{% static 'base/Framework.PNG' %}"
        style="height: auto; width: 100%; object-fit: contain"
      />
    </div>
    <div class="col-6">
      <p style="text-indent: 2em; text-align: justify">
        During my spare time, I channeled my passion for web development by
        building this personal website using a combination of frontend and
        backend technologies. To enhance the website's appearance, I utilized
        Bootstrap, HTML, and CSS to create an interactive and visually appealing
        frontend. In addition, I incorporated a backend framework, Django, to
        ensure the website was efficient and user-friendly. To store and manage
        data, I used SQLite, a robust database management system. Throughout the
        development process, I encountered challenges, but I used my
        problem-solving skills to overcome them and improve the functionality
        and appearance of the website. I am proud of this achievement and am
        excited to continue enhancing my skills in web development.
      </p>
    </div>
  </div>

  <hr />
</div>

{% endblock %}

personalWeb/base/templates/base/c.html
{% load static %}

<link rel="stylesheet" href="{% static 'base/contact.css' %}" />

<div class="container" id="contactForm">
  <h1 class="text-center">Contact Us</h1>
  <p class="text-center">Please fill out the form below to contact me!</p>
  <div class="form mx-auto" style="width: 100%">
    <form
      action="{% url 'base:contact_submit' %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          <label
            >First Name: <input name="firstName" type="text" required
          /></label>
        </div>
        <div class="col-md-6">
          <label
            >Last Name: <input name="lastName" type="text" required
          /></label>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <label
            >Email Address: <input name="email" type="email" required
          /></label>
        </div>
        <div class="col-md-6">
          <label
            >Phone Number: <input name="phone" type="tel" required
          /></label>
        </div>
      </div>

      <label
        >How did you find this website?
        <select name="find">
          <option value="">Select</option>
          <option value="1">LinkedIn</option>
          <option value="2">Resume</option>
          <option value="3">GitHub</option>
          <option value="4">Other</option>
        </select>
      </label>
      <label
        >Additional Infomation:
        <textarea
          name="textBox"
          rows="3"
          placeholder="If you have something you like me to know..."
        ></textarea>
      </label>
      <label>Upload File: <input name="file" type="file" /></label>

      <label
        ><input class="term" name="term" type="checkbox" style="width: 5%"/>I agree to the
        <a href="">terms and conditions</a></label
      >

      <div class="text-center">
      <button
        class="btn btn-success"
        id="submit"
        style="width: 25%"
      >
        Submit
      </button>
      <div>
    </form>
  </div>
</div>

personalWeb/base/templates/base/cert.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %}


<!--- Adding Publication Model -->

<div class="container">
    <h1 class="text-center">Certification</h1>
    {% for c in certs %}
    <hr>
    <div class="row">
        <div class="col-6">
            <h2><a href = "{{c.url}}" target ="_blank">{{c.title}}</a></h2>
        </div>
        <div class="col-6">
            <span class="float-right">{{c.date}}</span>
        </div>
    </div>

    {% endfor %}
</div>


<hr>

{% endblock %}

personalWeb/base/templates/base/contact.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'base/contact.css' %}" />

<div class="container">
  <h1 class="text-center">Contact Us</h1>
  <p class="text-center">Please fill out the form below to contact me!</p>
  <div class="form mx-auto" style="width: 70%">
    <form
      action="{% url 'base:contact_submit' %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <fieldset>
        <label
          >First Name: <input name="firstName" type="text" required
        /></label>
        <label>Last Name: <input name="lastName" type="text" required /></label>
      </fieldset>
      <fieldset>
        <label
          >Email Address: <input name="email" type="email" required
        /></label>
        <label>Phone Number: <input name="phone" type="tel" required /></label>
      </fieldset>
      <fieldset>
        <label
          >How did you find this website?
          <select name="find">
            <option value="">Select</option>
            <option value="1">LinkedIn</option>
            <option value="2">Resume</option>
            <option value="3">GitHub</option>
            <option value="4">Other</option>
          </select>
        </label>
        <label
          >Additional Infomation:
          <textarea
            name="textBox"
            rows="3"
            placeholder="If you have something you like me to know..."
          ></textarea>
        </label>
        <label>Upload File: <input name="file" type="file" /></label>
      </fieldset>

      <fieldset>
        <label
          ><input class="term" name="term" type="checkbox" />I agree to the
          <a href="">terms and conditions</a></label
        >
      </fieldset>
      <button id="submit">Submit</button>
    </form>
  </div>
</div>

{% endblock %}

personalWeb/base/templates/base/contact_submit.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%} {% load static %} {% block content %}
<div class="container">
  <h1 class="text-center">Contact Us</h1>
  <p class="text-center">
    Thank you for reaching out! Your message has been received.
  </p>
  <div class="text-center">
    <button class="btn btn-success">
      <a class="text-reset" href="/home">Return back to homepage</a>
    </button>
  </div>
</div>
{% endblock %}

personalWeb/base/templates/base/hac.html
{% extends 'main.html'%} {% load static %} {% block content %}
<div class="container text-center">
  <h2 style="padding: 10px; margin: 10px">Heart Attack Classification App</h2>
</div>

<hr />
<div class="container text-center justify-content-center align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-7 d-flex align-items-center justify-content-center">
        <img src="{% static 'base/EDA.PNG' %}" style="width: 100%" />
      </div>
      <div class="col-5">
        <p style="text-align: justify; text-indent: 1em">
          Exploratory data analysis (EDA) with Pandas and Seaborn libraries can
          be used to preprocess the heart attack dataset by handling missing
          values, outliers, and scaling features. After EDA, multiple machine
          learning models, including logistic regression, decision trees, random
          forests, support vector machines, and neural networks, can be trained
          for heart attack classification. By using GridSearchCV to tune the
          hyperparameters of these models, their performance can be optimized.
          Additionally, a neural network model can be used to achieve high
          accuracy by training on large amounts of data. Overall, EDA with
          Pandas and Seaborn, followed by the use of multiple machine learning
          models optimized with GridSearchCV and incorporating a neural network
          model, can accurately predict heart attack risk.
        </p>
      </div>
    </div>
  </div>

  <p>
    This is a link to the EDA and ML optimization code:
    <a
      href="https://github.com/Christopherc0923/Mini-Projs/blob/main/Heart%20Attack%20Classification/Temp.ipynb"
      target="_blank"
      >Link</a
    >
  </p>

  <hr />

  <div class="container">
    <div class="row">
      <div
        class="col-5 d-flex flex-column align-items-center justify-content-center"
      >
        <h3 style="width: 85%">
          Are you concerned about your risk of heart attack?
        </h3>
        <p style="text-align: justify; text-indent: 1em; width: 85%">
          Simply fill out our form on the right to find out. Our form allows you
          to input various health conditions such as age, gender, blood
          pressure, cholesterol levels, and smoking habits. Our advanced
          algorithm uses a decision tree machine learning model to accurately
          predict your risk of heart attack based on your individual health
          profile. By providing personalized information based on the latest
          scientific research, our form empowers you to take control of your
          heart health and make informed decisions about your lifestyle and
          medical care.
        </p>
      </div>
      <div class="col-7 d-flex align-items-center justify-content-center">
        <img src="{% static 'base/heart_classification_pic1.PNG' %}" />
      </div>
    </div>
  </div>

  <hr />

  <div
    class="container d-flex flex-column justify-content-center align-items-center text-center"
  >
    <h3>Results</h3>
    <p style="text-align: justify; text-indent: 1em; width: 50%">
      In our results section, you can see your previous form entries and their
      estimated risk of heart attack. This allows you to track changes in your
      health over time and take proactive steps to manage your risk. Our results
      section is a valuable tool for staying informed and making informed
      decisions about your heart health.
    </p>
    <img
      src="{% static 'base/heart_classification_res.PNG' %}"
      style="width: 75%"
    />
  </div>
</div>
{% endblock %}

personalWeb/base/templates/base/home.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'base/home.css' %}" />
<br />

<div class="container d-flex vertical-align">
  <div class="row">
    
    <br />
    <div class="col-md-6">
      <img
        src="{% static 'base/DiscordIcon.png' %}"
        style="height: auto; width: 80%; object-fit: contain"
      />
    </div>
    <div class="col-md-6 " style="padding: 30px">
      <h4>Hello, I am Christopher Chan!</h4>
      <p style="text-align: justify;">I work at Intel as Process Engineer. I use the data generated from wafer manufacturing to create data solutions for my team!</p>
      <p>I am looking for an opportunity in data science or software development</p>
      <button class="btn btn-outline-primary">
        <a href="{% url 'base:about' %}">
          About me <i class="fas fa-user"></i>
        </a>
      </button>

      <button class="btn btn-outline-primary">
        <a href="{% url 'base:contact' %}">Contact Me</a>
      </button>
    </div>
  </div>
</div>

<hr />


<!-- Legacy Project Model Display
<br />
<div class="container">
  <h2 class="text-center fs-1" style="padding: 10px">Projects</h2>
  <div class="row">
    {% for project in projects %} {% if forloop.counter0|divisibleby:3 %}
  </div>
  <div class="row">
    {% endif %}
    <div class="col-md-4" style="padding: 10px">
      <div class="card" style="padding: 20px">
        <div style="min-height: 120px">
          <h3 class="card-title text-center py-3">
            <a
              href="{{project.url}}"
              style="text-decoration: none; color: black"
              >{{project.title}}</a
            >
          </h3>
        </div>
        <a href="{{project.url}}">
          <img
            src="{{project.image.url}}"
            class="card-img-top"
            style="height: 300px; object-fit: contain"
          />
        </a>
        <div class="card-body">
          <p
            class="card-text"
            style="text-align: justify; min-height: 160px; text-indent: 1em"
            title="{{project.description}}"
          >
            {{project.description|truncatechars:240}}
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
-->

<!--- Adding Project Model -->

<div class="container">
  <h2 class="text-center fs-1" style="">My Projects</h2>
  <div id="myCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel" style="">
    <!-- Project Carousel -->
    <div class="carousel-inner container justify-content-center align-items-center" style="width: 80%; padding: 20px;">
      {% for project in projects %}
        {% if forloop.counter0|divisibleby:2 %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <div class="row">
              {% endif %}
              <div class="col-md-6 p-2" style="">
                <div class="card" style="">
                  <div style="min-height: 120px">
                    <h3 class="card-title text-center py-3">
                      <a href="{{project.url}}" style="text-decoration: none">{{project.title}}</a>
                    </h3>
                  </div>
                  <a href="{{project.url}}" style="height: 300px;">
                    <img src="{{project.image.url}}" class="card-img-top" style="height: 300px; object-fit: contain"/>
                  </a>
                  <div class="card-body">
                    <p class="card-text" style="text-align: justify; min-height: 200px; text-indent: 1em" title="{{project.description}}">
                      {{project.description|truncatechars:250}}
                    </p>
                  </div>
                </div>
              </div>
              {% if forloop.last or forloop.counter0|add:1|divisibleby:2 %}
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <!-- Slider -->
    <ol class="carousel-indicators" style="position: relative">
      <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
      <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
      <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
    </ol>
    
    <!-- Buttons to move left and right -->
    <a class="carousel-control-prev text-dark" href="#myCarousel" role="button" data-bs-slide="prev" style="width: 10%">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next text-dark" href="#myCarousel" role="button" data-bs-slide="next" style="width: 10%">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>
</div>

<hr />

<div class="container text-center">
  <h2>Skills</h2>
  {% for skill in skills %}
  <span>{{skill.title}}{% if not forloop.last %},{% endif %}</span>
  {% endfor %}
</div>

<hr />


<div class="container">
  <h1>Blinking Span Example</h1>
  <span id="blinkingSpan" class="blinking-span"></span>
</div>

<script>
  const words = ['Word 1', 'Word 2', 'Word 3'];
  let currentWordIndex = 0;
  const blinkingSpan = document.getElementById('blinkingSpan');
  
  function updateBlinkingText() {
    blinkingSpan.textContent = words[currentWordIndex];
    currentWordIndex = (currentWordIndex + 1) % words.length;
  }
  
  setInterval(updateBlinkingText, 2000); // Change text every 2 seconds
</script>

<hr/>

{% include './c.html' %}

{% endblock %}



</div>

personalWeb/base/templates/base/mlproj.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %}


<!--- Adding Publication Model -->
<div class="container">
    <h1>Machine Learning Projects</h1>    
</div>
<div class="container">
    <ul>
        <li>Defining the problem statement</li>
        <li>Collecting the data</li>
        <li>Cleaning the data</li>
        <li>Modeling the data</li>
        <li>Model building</li>
        <li>Visualizing the data</div>
        <li>Model Deployment</li>
    </ul>
</div>

<div class="container">
    <h1 class="text-center">Machine Learning Projects</h1>
    {% for m in MLs %}
    <hr>
    <div class="row">
        <h2><a href = "{{m.url}}" target ="_blank">{{m.title}}</a></h2>
        </p>{{m.description|truncatechars:500}}</p>
        <img src = "{{m.image.url}}" style="height: 300px; object-fit: contain">
    </div>

    {% endfor %}
</div>


<hr>

{% endblock %}

personalWeb/base/templates/base/publication.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%} {% load static %} {% block content %}

<!--- Adding Publication Model -->

<div class="container">
  <h1 class="text-center">My Publications</h1>
  {% for p in publications %}
  <hr />
  <div class="row">
    <h2><a href="{{p.url}}" target="_blank">{{p.title}}</a></h2>
    <p style="text-indent: 2em">{{p.description|truncatechars:500}}</p>
    <img src="{{p.image.url}}" style="height: 300px; object-fit: contain" />
  </div>

  {% endfor %}
</div>

<hr />

{% endblock %}

personalWeb/base/templates/base/resume.html
{% extends 'main.html'%}

{% load static %}



{% block content %}
<div class="container text-center">
    <h2>Resume</h2>
</div>

<div class="container text-center">
    <iframe src="{% static 'base/Chan Christopher Resume 2023.pdf' %}" width="800" height="1100"></iframe>
</div>
<hr>
{% endblock %}

personalWeb/base/templates/base/test.html
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
    <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
    <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item">
      <img src="" class="d-block w-100" alt="..." />
    </div>
    <div class="carousel-item">
      <img src="" class="d-block w-100" alt="..." />
    </div>
    <div class="carousel-item">
      <img src="" class="d-block w-100" alt="..." />
    </div>
  </div>
  <a
    class="carousel-control-prev"
    href="#myCarousel"
    role="button"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#myCarousel"
    role="button"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>

personalWeb/base/templates/base/todo.html
{% extends 'main.html'%} {% load static %} {% block content %}
<div class="container text-center">
  <h2>Todo Application</h2>
</div>

<hr />
<div class="container text-center justify-content-center align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-7 d-flex align-items-center justify-content-center">
        <img src="{% static 'base/todoCreate.PNG' %}" style="width: 60%" />
      </div>
      <div class="col-5">
        <p style="text-align: justify; text-indent: 1em">
          Our to-do list application allows you to easily add new entries to
          your to-do list. Simply navigate to the todo section and type in the
          task you need to complete. Once you've added your task, you can also
          include a due date or any additional notes or reminders. Our
          user-friendly interface makes it simple to manage your tasks and stay
          organized, ensuring that you never forget an important task again.
          With our to-do list application, you can quickly and easily manage
          your tasks and accomplish your goals.
        </p>
      </div>
    </div>
  </div>

  <hr />

  <div class="container">
    <div class="row">
      <div
        class="col-5 d-flex flex-column align-items-center justify-content-center"
      >
        <p style="text-align: justify; text-indent: 1em; width: 85%">
          After adding entries to your to-do list, you can view them in the todo
          section of our application. From there, you can select and delete
          individual entries using the 'Delete' button next to each task. If you
          want to delete all tasks at once, you can use the 'Delete All' button
          at the bottom of the list. Our application makes it simple to manage
          and organize your to-do list, so you can focus on completing your
          tasks and achieving your goals.
        </p>
      </div>
      <div class="col-7 d-flex align-items-center justify-content-center">
        <img src="{% static 'base/todoList.PNG' %}" style="width: 70%" />
      </div>
    </div>
  </div>
</div>
{% endblock %}

personalWeb/templates/nav.html
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
/>

<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
  <div class="container-fluid">
    <i class="fab fa-discord"></i>
    <a class="navbar-brand" href="/">Chris Chan</a>

    <!-- Add the following button element for mobile menu -->
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home">Home</a>
        </li>
        <!--
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:about' %}">About</a>
        </li>
        -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:resume' %}">Resume</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:cert' %}">Certification</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:publication' %}"
            >Publication</a
          >
        </li>
        <!-- 
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:contact' %}">Contact</a>
        </li>
        -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'base:adminPage' %}">Admin</a>
        </li>

        <li class="nav-item">
          <button id="btnSwitch" class="nav-link btn">Toggle</button>
        </li>
      </ul>
    </div>
  </div>
</nav>